### ISSUE TITLE
missing zfs module

### ISSUE THREAD

**Issue by funkaster** [raphael/linux-samus#138]
It would be great if you could add the zfs module, or maybe some instructions on how to add extra modules.

**Comment by ehegnes** [comment]
@funkaster, I assume you mean the [native ZFS port](http://zfsonlinux.org/) and not the FUSE-based solution. From what I understand, the original ZFS can not be legally distributed in a binary due to evil licensing. It's up to @raphael of course, but I think the samus kernel remain be as vanilla as possible.

I always apply at least one patchset to the samus kernel before compiling and installing — I would be glad to write some documentation on the matter! @funkaster what distro do you use?

FWIW, I still think it might be nice to have submodule splitting by wanted feature sets (-ck patchset, ZFS on Linux, AUFS, BFQ, etc...) as mentioned in issue #109, but I haven't gotten around to finalizing the PPA.

**Comment by funkaster** [comment]
I'm closing this, because using dkms solves the problems (see https://wiki.archlinux.org/index.php/ZFS#DKMS)
