### ISSUE TITLE
PPA repo for Ubuntu

### ISSUE THREAD

**Issue by idvoretskyi** [raphael/linux-samus#158]
Hello,

Is there any repo with the *.deb files for Ubuntu? If no, any thoughts about establishing it?

**Comment by raphael** [comment]
There isn't one, I've been looking for someone to set one up though :)

**Comment by idvoretskyi** [comment]
@raphael I'll be happy to handle that!

Please, confirm that repo PPA can me named "linux-samus" and use this repo as a source.

**Comment by raphael** [comment]
Awesome! the name makes sense, I had done an attempt at https://launchpad.net/~simon-raphael/+archive/ubuntu/linux-samus but could never get it to work fully because I didn't have all the required tooling on my Arch Linux distro and I'm just not familiar enough with hosting a kernel PPA (yes it would have to be a source PPA).

**Comment by idvoretskyi** [comment]
As 4.9 upstream confirmed as working, closing the issue.

**Comment by colemickens** [comment]
What do you mean by "upstream confirmed as working"? I still couldn't get sound/audio working on 4.9 mainline.

**Comment by raphael** [comment]
This kernel does not patch the mainline anymore - it only provides an optimized configuration. So mainstream should work.

**Comment by ehegnes** [comment]
4.9.0? Which minor revision is confirmed to be working?

**Comment by raphael** [comment]
All of them :)
