### ISSUE TITLE
touch screen after suspend?

### ISSUE THREAD

**Issue by recri** [raphael/linux-samus#186]
4.10.0-ph+ isn't restoring the touch screen after suspend for me.  Can anyone confirm?

Running (cd linux-samus/setup/scripts/touchpad && ./enable-atmel.sh) fixes the problem.

**Comment by raphael** [comment]
It works for me, does it happen every time?

**Comment by colemickens** [comment]
One out of forty-ish times my touchscreen is non-responsive after resuming from suspend. The script also fixes it when this rare thing happens.

(I also wonder if my has hardware issues though, because of the thing it often does where it straight up doesn't come out of suspension properly (even with stable ChromeOS... really baffling).)

**Comment by raphael** [comment]
I don't use the touchscreen on a regular basis (only when people report that it doesn't work :) ) so it is possible that it doesn't always work and that I haven't realized it. I do however use suspend all the time (practically never completely shutdown, only for kernel upgrades/testing) and haven't had issues with it in a long time (since 4.3 pretty much).

**Comment by recri** [comment]
Well, it appears less reliably broken now that I've rerun the
enable-atmel.sh script.  I'll check on it the next few days.  I suspend at
least once a day and almost always try to use the touchscreen to play
mahjong.elf.org because I pretend that I'm testing it.

-- rec --

**Comment by daspliff** [comment]
Thank you! This has also been happening randomly for me, maybe also one out of fortyish times, where coming out of suspend my trackpad and touchscreen would freeze. I would have to force a restart to reset it. I now have a script to fix it.

**Comment by recri** [comment]
There may be a problem here, but I haven't seen reliable evidence of it.
