### ISSUE TITLE
How can others work on this project?

### ISSUE THREAD

**Issue by christianbundy** [raphael/linux-samus#211]
Hi there! I've noticed that this project is a bit behind Linux `v4.16.y` and I'd like to help, but I've been having trouble trying to understand how this repository is set up. In the past I've just used `git clone` to pull your AUR repo and run `makepkg -si`, but while trying to mitigate #210 I've realized that I don't think I can build the repo from source.

I've read through all of the documentation and am under the impression that `scripts/build.sh` is a good place to start, but it looks like it's looking for the non-existent `build/linux-patched`. I've used `git grep` but can't find anything that could possibly generate `build/linux-patched`, and the [patch references](https://github.com/raphael/linux-samus/blob/master/scripts/archlinux/PKGBUILD#L18-L23) I found point to non-existent files.

After doing a deep-dive into the Git history I can see that there _used_ to be files like [`scripts/patch.sh`](https://github.com/raphael/linux-samus/blob/7c8182aa4468848cd4d3fd6be54994d334f92a07/scripts/patch.sh) that look like they're capable of applying patches, but that seems to have been deleted. My best guess is that you've applied the patches to `build/linux` and are just manually copy and pasting changes from the Linux `v4.16.y` tree, which seems like `build/linux` _is_ the patched version of Linux, which is getting changes copied from the stable tree and pasted into this repo. Could that be right? If so, I'd love to help out and delete all of the outdated scripts and documentation in the repo.

Given the above background info, I have two questions:

- How can others test `makepkg` locally to build/install and make sure their changes work?
- How can others upgrade Linux in this repo without causing a headache for you?

Thanks for working on this great kernel, it makes my life a hell of a lot easier.

**Comment by raphael** [comment]
Thank you for the interest! As noted in the README there is no need to patch the kernel anymore to get support for all the hardware. This is why the patch scripts were deleted. `linux-patched` is just a vanilla clone of the linux source code. `build.sh` is indeed the right script for building the kernel. You may also be interested in the platform specific build scripts in `scripts/archlinux` and `scripts/debian`. Finally there's a `release.sh` script which is what I use to build new releases. As you've noted I haven't built one in the past few releases because the kernel wouldn't compile. This is fixed as of `4.16.8` and I'm in the process of building a new release now.

**Comment by christianbundy** [comment]
Thanks for the quick response! It sounds like this repo contains a few different things:

- Build/release meta-scripts
- Vanilla kernel, except:
  - Added `exit 0` in `scripts/depmod.sh`
  - Commented out five instances of `$(MAKE) clean` in `scripts/package/Makefile`
  - Commented out one instance of `$(MAKE) clean` in `scripts/package/builddeb`
  - Made changes to `.config`:
    - `CONFIG_AUDIT=y`
    - `CONFIG_AUDITSYSCALL=y`
    - `CONFIG_AUDIT_TREE=y`
    - `CONFIG_AUDIT_WATCH=y`
    - `CONFIG_DEFAULT_SECURITY="apparmor"`
    - `CONFIG_DEFAULT_SECURITY_APPARMOR=y`
    - `CONFIG_INTEL_PMC_CORE=m`
    - `CONFIG_LOCALVERSION="-ph"`
    - `CONFIG_MCORE2=y`
    - `CONFIG_NODES_SHIFT=2`
    - `CONFIG_SECURITY_APPARMOR=y`
    - `CONFIG_SECURITY_APPARMOR_BOOTPARAM_VALUE=1`
    - `CONFIG_SECURITY_APPARMOR_HASH_DEFAULT=y`
    - `CONFIG_SECURITY_APPARMOR_HASH=y`
    - `CONFIG_TOUCHSCREEN_ATMEL_MXT=y`
    - `CONFIG_X86_INTEL_MPX=y`
    - `CONFIG_X86_INTEL_USERCOPY=y`
    - `CONFIG_X86_P6_NOP=y`
    - `CONFIG_X86_USE_PPRO_CHECKSUM=y`
- Utility scripts
  - Audio management
  - Brightness increase/decrease
  - Keyboard shortcuts
  - Enabled Atmel configuration
  - Intel graphics acceleration config file
- Build artifacts
  - Arch packages
  - Debian packages (and metadata)

Assuming that all of the `CONFIG_` changes are intentional and still relevant, do you think it would be appropriate to remove the kernel from this repo and include a small patch for the vanilla kernel instead?

**Comment by ehegnes** [comment]
With respect to `CONFIG_NODES_SHIFT`, I don't think we can even properly use NUMA—our machines only have a single CPU socket. It might as well not be there.

I'd be glad to help document the configuration choices that this repo has made. Would this perhaps make more sense to document in a wiki section rather than including it in the README?

**Comment by raphael** [comment]
@christianbundy @ehegnes  Would any of you be interested in taking over maintaining this repo and releasing new kernel versions? I'm finding myself with less and less time to spend on this.

**Comment by ehegnes** [comment]
@raphael, I'd be happy to give it a shot, long as you can outline the process you go through. It's been while since I dug into the scripts.

**Comment by raphael** [comment]
Great! the steps necessary to release a new kernel version are described in [RELEASE.md](https://github.com/raphael/linux-samus/blob/master/RELEASE.md). They are automated in the script `release.sh` located under the `scripts` folder.

The release process relies on the Linux kernel repo being cloned under `scr/linux-patched` (the term `linux-patched` is historic since there is no patching necessary anymore). The steps push the new package  to the AUR which requires push access to the `linux-samus4` repo. I can add you as a maintainer if you provide me with your username.

Maybe you can try running the `release.sh` script and see if you can get it to work then ask here if something isn't working quite right?

Thank you!

**Comment by christianbundy** [comment]
I'd be happy to help co-maintain or work on any future versions -- I've recently packaged the runtime scripts (like `enable-speakers.sh`) as an AUR package called [`samus-scripts`](https://aur.archlinux.org/packages/samus-scripts/ and I've been maintaining a small personal fork based on upstream [`linux`](https://www.archlinux.org/packages/core/x86_64/linux/) for a few weeks as well.

**Comment by ehegnes** [comment]
@christianbundy Perhaps we should both maintain this repo so that it is more manageable. Nice job packaging the scripts.

@raphael I just created an AUR account—the username is the same as my GitHub.

**Comment by raphael** [comment]
@ehegnes I've added you as a co-maintainer of the AUR package. 

@christianbundy let me know what your AUR username is and I'll add you as well.

Thank you guys!

**Comment by christianbundy** [comment]
Thanks @raphael! I've got the same username on AUR: https://aur.archlinux.org/account/christianbundy

**Comment by raphael** [comment]
Alright both of you are co-maintainers now.
