### ISSUE TITLE
Kernel build error when building from source

### ISSUE THREAD

**Issue by colemickens** [raphael/linux-samus#86]
This looks similar to #1.

When I try to build I get:

```
/tmp/nix-build-linux-4.4.0.drv-0/linux-samus-src-v4.4-3/sound/soc/soc-generic-dmaengine-pcm.c:333:3: error: unknown field 'probe_order' specified in initializer
   .probe_order = SND_SOC_COMP_ORDER_LATE,
   ^
```

Full log: https://gist.github.com/anonymous/c3abb0fc2b66820c99d5

There's a definite possibility that this is user error. First time building a kernel in NixOS...

**Comment by colemickens** [comment]
Do I need to move a config file into place ahead of time (reading comments from #1)? It seemed like the symlink was right.

**Comment by ehegnes** [comment]
That's strange. It looks like [`soc-generic-dmaengine-pcm.c`](https://github.com/raphael/linux-samus/blob/master/build/linux/sound/soc/soc-generic-dmaengine-pcm.c) hasn't changed since `4.2-1`. I always build from source, and I successfully built moments ago.

I wouldn't chalk that up to a config issue -- it's a C issue.

This file may have missed an update, because `probe_order` certainly isn't defined in [`include/sound/soc.h#L699-709`](https://github.com/raphael/linux-samus/blob/master/build/linux/include/sound/soc.h#L699-L709) -- at least not in this repo. It is, however, defined in the vanilla repo: https://github.com/torvalds/linux/blob/v4.4-rc3/include/sound/soc.h#L750-L775.

I'm firstly confused as to why my build didn't fail. I am also confused about why `soc.h` is wrong -- unless this tree is not using the vanilla base?

**Comment by colemickens** [comment]
Two things:

1. I agree that the file hasn't changed; that was the first place I looked as well. If you note though, the error and approx source location are the same as in Issue #1 

2. Your other PC, @ehegnes, revealed what might be the problem. The Nix definition for my kernel moves the `build` directory because it expects the kernel source at the top level. That's possibly breaking @raphael 's symlinked config and causing me to get into the same state that caused #1.

At least, that's my guess. I'm going to either pull your PR (it looked like you removed the symlink business) or change the nix definition to attempt to workaround.

**Comment by raphael** [comment]
Just to confirm that I'm able to compile `build/linux` with no issue from a fresh clone.

**Comment by ehegnes** [comment]
Sorry, my earlier nonsense about `soc.h` being wrong/outdated is unsubstantiated. I forgot that the patchset is coming from the ChromeOS base, not from upstream Linux.

**Comment by raphael** [comment]
Going to close for now, I don't think it's an issue with this repo. Please re-open if needed.
